name: DAST
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL to scan (e.g., https://testphp.vulnweb.com)"
        required: true
        type: string

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ github.event.inputs.target_url }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            zap.out
