name: SAST
on:
  workflow_dispatch: {}  # allows API/manual trigger

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript # change to your language(s) if needed
      - uses: github/codeql-action/analyze@v3
