name: SAST
on:
  workflow_dispatch: {}

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript   # change to your language(s)
      - uses: github/codeql-action/analyze@v3

      # Export a simple findings summary to JSON for the report job
      - name: Export CodeQL summary (counts only)
        run: |
          echo '{"critical":0,"high":0,"medium":0,"low":0}' > sast_counts.json
          # NOTE: This is a simple placeholder.
          # If you want real counts: use GitHub REST API in a later step or Defender for DevOps.
      - uses: actions/upload-artifact@v4
        with:
          name: sast-summary
          path: sast_counts.json
